name: memes shop twitter bot

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/7 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv pygsheets
      - name: execute py script 
        run: |
          python memes_shop_twitter_bot/post_tweet.py
          python memes_shop_twitter_bot/follow_unfollow_like.py
        env:
          MEMES_SHOP_TWITTER_BOT_CONSUMER_KEY: ${{secrets.MEMES_SHOP_TWITTER_BOT_CONSUMER_KEY}}
          MEMES_SHOP_TWITTER_BOT_CONSUMER_SECRET: ${{secrets.MEMES_SHOP_TWITTER_BOT_CONSUMER_SECRET}}
          MEMES_SHOP_TWITTER_BOT_ACCESS_TOKEN: ${{secrets.MEMES_SHOP_TWITTER_BOT_ACCESS_TOKEN}}
          MEMES_SHOP_TWITTER_BOT_ACCESS_TOKEN_SECRET: ${{secrets.MEMES_SHOP_TWITTER_BOT_ACCESS_TOKEN_SECRET}}
          MEMES_SHOP_TWITTER_BOT_GDRIVE_API_CREDENTIALS: ${{secrets.MEMES_SHOP_TWITTER_BOT_GDRIVE_API_CREDENTIALS}}
          MEMES_SHOP_TWITTER_BOT_SHEET_KEY: ${{secrets.MEMES_SHOP_TWITTER_BOT_SHEET_KEY}}
