name: quotes pinterest bot

on:
  schedule:
    - cron: "*/7 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv imgbbpy Pillow python-pinterest social-post-api 
      - name: execute py script 
        run: |
          python quotes_pinterest_bot/pinterest_pins.py
        env:
          QUOTES_PINTEREST_BOT_ACCESS_TOKEN: ${{secrets.QUOTES_PINTEREST_BOT_ACCESS_TOKEN}}
          QUOTES_PINTEREST_BOT_AYRSH: ${{secrets.QUOTES_PINTEREST_BOT_AYRSH}}
          QUOTES_META_BOT_IMGBB_CLIENT: ${{secrets.QUOTES_META_BOT_IMGBB_CLIENT}}